// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlJD4O43_Ytn_54rxkLoxMN98yj0Z3iWc',
    appId: '1:524763655181:web:8cf4c7456c468083c7b944',
    messagingSenderId: '524763655181',
    projectId: 'fir-example-2683d',
    authDomain: 'fir-example-2683d.firebaseapp.com',
    storageBucket: 'fir-example-2683d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy9gwdixBn7xXVyBoyAb1J4L5nZftvCSo',
    appId: '1:524763655181:android:7cb3e59e935f5e1cc7b944',
    messagingSenderId: '524763655181',
    projectId: 'fir-example-2683d',
    storageBucket: 'fir-example-2683d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbvltJ18ogUiE1WBwO3lk0vsgBiUBwF08',
    appId: '1:524763655181:ios:1f8f712c74813034c7b944',
    messagingSenderId: '524763655181',
    projectId: 'fir-example-2683d',
    storageBucket: 'fir-example-2683d.appspot.com',
    androidClientId: '524763655181-h1b8b9isrlvcuujnp9tl711c7uu48cer.apps.googleusercontent.com',
    iosClientId: '524763655181-1lniqdjj7dkq98eb9nm7bm6amrd7omfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbvltJ18ogUiE1WBwO3lk0vsgBiUBwF08',
    appId: '1:524763655181:ios:1f8f712c74813034c7b944',
    messagingSenderId: '524763655181',
    projectId: 'fir-example-2683d',
    storageBucket: 'fir-example-2683d.appspot.com',
    androidClientId: '524763655181-h1b8b9isrlvcuujnp9tl711c7uu48cer.apps.googleusercontent.com',
    iosClientId: '524763655181-1lniqdjj7dkq98eb9nm7bm6amrd7omfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireBase',
  );
}
